# ----------------------------------------------------------- #
# Note: this file originates in ahmadnassri/template-node-lib #
# ----------------------------------------------------------- #

ts: false
jsx: false
flow: false
coverage: true
browser: false
color: true
coverage-report: html
