# ----------------------------------------------------------- #
# Note: this file originates in ahmadnassri/template-node-lib #
# ----------------------------------------------------------- #

version: '3.8'

x-node: &node
  tty: true
  volumes:
    - type: bind
      source: .
      target: /app
  working_dir: /app
  command: npm run test

services:
  # ---- super-linter ---- #
  lint:
    image: github/super-linter:slim-v4
    volumes:
      - ./:/github/workspace
    environment:
      RUN_LOCAL: 'true'
      LOG_LEVEL: 'ERROR'
      MULTI_STATUS: 'false'
      VALIDATE_JSCPD: 'false'
      IGNORE_GITIGNORED_FILES: 'true'
      DEFAULT_WORKSPACE: /github/workspace
      FILTER_REGEX_EXCLUDE: '/github/workspace/README.md|test/fixtures/*'

  # ---- readme generator ---- #
  readme:
    image: pandoc/core:2.13
    volumes:
      - ./:/data
    command: --defaults=.pandoc.yml

  # ---- test runner ---- #
  test:
    <<: *node
    image: node:alpine
    depends_on:
      - node12
      - node14
      - node15

  node12:
    <<: *node
    image: node:12-alpine

  node14:
    <<: *node
    image: node:14-alpine

  node15:
    <<: *node
    image: node:15-alpine
