#!/usr/bin/env bash

REPORTER=$PWD/.scripts/cc-test-reporter

if [ ! -e "$REPORTER" ]; then
  curl -sL https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > "$REPORTER"
  chmod +x "$REPORTER"
fi

$REPORTER "$@"
