# ------------------------------------------------------------- #
# Note: this file is automatically managed in template-template #
# ------------------------------------------------------------- #

name: auto-merge

on: pull_request_target

jobs:
  auto-merge:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.4
        with:
          github-token: ${{ secrets.GH_TOKEN }}
