# ----------------------------------------------------------- #
# Note: this file originates in ahmadnassri/template-template #
# ----------------------------------------------------------- #

name: commit-lint

on: [push, pull_request]

jobs:
  deduplicate:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    # run on external PRs, but not on our internal PRs
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - run: echo ::info ::duplicate check ran successfully

  commit-lint:
    timeout-minutes: 5

    needs: deduplicate

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-commit-lint@v1
        with:
          config: .github/linters/.commit-lint.yml
