name: test

on: [ push, pull_request ]

env:
  NODE_ENV: test

jobs:
  deduplicate:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    # run on external PRs, but on internal PRs as they'll be run by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - run: echo ::warning ::skipped duplicate run

  audit:
    timeout-minutes: 5

    needs: deduplicate

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2.1.5
      - uses: actions/checkout@v2
      - run: npm audit --audit-level=critical

  strategy:
    timeout-minutes: 5

    needs: deduplicate

    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.parse.outputs.matrix }}

    steps:
      - uses: actions/checkout@v2
      - id: parse
        run: echo "::set-output name=matrix::$(jq -c . < .github/matrix.json)"

  test:
    needs: [ strategy, audit ]

    timeout-minutes: 5


    strategy:
      matrix: ${{ fromJSON(needs.strategy.outputs.matrix) }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: ${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
      - run: npm run test:ci
